app/src/main/java/com/getcode/view/main/account/AccountHome.kt

This PR adds an icon for the linked number icon in account settings.

Linked Phone number Icon ✅

---

app/src/main/java/com/getcode/view/main/giveKin/BaseAmountCurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheetViewModel.kt

also subscribeOn/observeOn for flows

fix(givekin): check entered amount against balance for continue enabled

---

api/src/main/java/com/getcode/model/CodePayload.kt
api/src/main/java/com/getcode/model/Fiat.kt
api/src/main/java/com/getcode/model/Kin.kt
api/src/main/java/com/getcode/network/repository/PaymentRepository.kt
api/src/main/java/com/getcode/network/repository/SendTransactionRepository.kt
api/src/main/java/com/getcode/utils/DataSlice.kt
api/src/main/java/com/getcode/utils/Double.kt

Adds parsing support into CodePayload for payment request protocol.
UI integration to come.

feat(api): add support for Kind.RequestPayment

---

api/build.gradle.kts
api/src/main/java/com/getcode/network/client/Client_Transaction.kt
api/src/main/java/com/getcode/network/repository/TransactionRepository.kt
app/src/main/java/com/getcode/data/transactions/HistoricalTransactionUiModel.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/navigation/screens/Modals.kt
app/src/main/java/com/getcode/view/main/account/AccountDebugBuckets.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheet.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheetViewModel.kt
buildSrc/src/main/java/Dependencies.kt

Next step will be caching the transactions to database instead of memory for improved time to screen
https://github.com/code-payments/code-android-app/assets/1652321/72e97b5d-4cfb-4d9d-9319-3551d9fa75cc

feat: update BalanceSheet to new VM; cache historical transactions and fold in updates

---

app/src/main/java/com/getcode/inject/AppModule.kt
app/src/main/java/com/getcode/navigation/core/BottomSheetNavigator.kt
app/src/main/java/com/getcode/navigation/screens/Graphs.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/navigation/transitions/SheetSlideTransition.kt
app/src/main/java/com/getcode/util/AndroidLocale.kt
app/src/main/java/com/getcode/util/Voyager.kt
app/src/main/java/com/getcode/util/locale/LocaleHelper.kt
app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmount.kt
app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmountViewModel.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectSheet.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectionSheet.kt
app/src/main/java/com/getcode/view/main/currency/CurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/BaseAmountCurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheet.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheetViewModel.kt

add activity scoping to VMs to ensure data loaded and available throughout lifecycle of app

feat: move currency to its own modal; show from give/withdrawal

---

app/src/main/java/com/getcode/navigation/core/BottomSheetNavigator.kt

This fixes dismissing sheets from inner screens (e.g sheet root -> push -> dismiss) popping the stack root again.

feat(navigation/bottomsheet): implement stack based sheet handling for stacks in secondary sheets

---

app/src/main/java/com/getcode/navigation/core/BottomSheetNavigator.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/navigation/screens/ModalScreens.kt
app/src/main/java/com/getcode/navigation/screens/Modals.kt
app/src/main/java/com/getcode/util/ModifierExt.kt
app/src/main/java/com/getcode/util/RecompositionHighlighter.kt
app/src/main/java/com/getcode/view/components/BottomBarContainer.kt
app/src/main/java/com/getcode/view/components/BottomBarView.kt
app/src/main/java/com/getcode/view/components/OtpBox.kt
app/src/main/java/com/getcode/view/components/SheetTitle.kt
app/src/main/java/com/getcode/view/components/TitleBar.kt
app/src/main/java/com/getcode/view/components/TopBarContainer.kt
app/src/main/java/com/getcode/view/login/LoginHome.kt
app/src/main/java/com/getcode/view/login/PhoneVerify.kt
app/src/main/java/com/getcode/view/main/account/AccountDebugOptions.kt
app/src/main/java/com/getcode/view/main/account/AccountDeposit.kt
app/src/main/java/com/getcode/view/main/account/AccountHome.kt
app/src/main/java/com/getcode/view/main/account/AccountSheetViewModel.kt
app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmountViewModel.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectionSheet.kt
app/src/main/java/com/getcode/view/main/currency/CurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/getKin/BuyAndSellKin.kt
app/src/main/java/com/getcode/view/main/getKin/GetKinSheet.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountArea.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheet.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheetViewModel.kt
app/src/main/java/com/getcode/view/main/home/DecorView.kt
app/src/main/java/com/getcode/view/main/home/components/BillManagementOptions.kt
app/src/main/java/com/getcode/view/main/home/components/HomeBottom.kt

* Work around M.clickable recomposition bug
* Add RecompositionHighlighter for future debugging purposes
* remember onBackClick/onCloseClick in Modals

chore: handle erroneous recompositions

---

api/src/main/java/com/getcode/model/IntentMetadata.kt
api/src/main/java/com/getcode/network/repository/ReceiveTransactionRepository.kt
api/src/main/java/com/getcode/network/repository/TransactionRepository.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

Use the rendezvous instead of the nonce for the transaction (was also present on main branch as well, but now that we derive the rendesvous key within the CodePayload this is now readily accessible)

fix: allow grabbing bills from iOS

---

app/src/main/java/com/getcode/view/main/home/DecorView.kt
app/src/main/java/com/getcode/view/main/home/HomeScan.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

additionally set toast to null _after_ animation runs

fix(home/toast): revert animation changes and remember toast to prevent recomp

---

api/src/main/java/com/getcode/model/PrefBool.kt
api/src/main/java/com/getcode/network/client/Client_Transaction.kt
api/src/main/java/com/getcode/network/repository/AccountDebugRepository.kt
api/src/main/java/com/getcode/utils/Flow.kt
app/src/main/java/com/getcode/manager/AuthManager.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/theme/Color.kt
app/src/main/java/com/getcode/theme/Theme.kt
app/src/main/java/com/getcode/util/AndroidVibrator.kt
app/src/main/java/com/getcode/util/vibration/Vibrator.kt
app/src/main/java/com/getcode/view/components/BottomBarView.kt
app/src/main/java/com/getcode/view/components/TopBarContainer.kt
app/src/main/java/com/getcode/view/main/account/AccountDebugOptions.kt
app/src/main/java/com/getcode/view/main/account/AccountDebugOptionsViewModel.kt
app/src/main/java/com/getcode/view/main/connectivity/ConnectionState.kt
app/src/main/java/com/getcode/view/main/connectivity/ConnectionStatusComponent.kt
app/src/main/java/com/getcode/view/main/connectivity/ConnectionStatusProvider.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectionSheet.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountArea.kt
app/src/main/java/com/getcode/view/main/home/DecorView.kt
app/src/main/java/com/getcode/view/main/home/HomeScan.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt
app/src/main/res/values/strings-universal.xml
app/src/main/res/values/strings.xml

chore(beta): add back vibrate on scan using haptic ticks

---

app/src/main/java/com/getcode/CodeAppState.kt
app/src/main/java/com/getcode/inject/ApiModule.kt
app/src/main/java/com/getcode/navigation/screens/ModalScreens.kt
app/src/main/java/com/getcode/util/IntSize.kt
app/src/main/java/com/getcode/util/ModifierExt.kt
app/src/main/java/com/getcode/view/components/BottomBarView.kt
app/src/main/java/com/getcode/view/components/CodeButton.kt
app/src/main/java/com/getcode/view/components/CodeKeyPad.kt
app/src/main/java/com/getcode/view/login/AccessKey.kt
app/src/main/java/com/getcode/view/login/CameraPermission.kt
app/src/main/java/com/getcode/view/login/PhoneConfirm.kt
app/src/main/java/com/getcode/view/login/PhoneVerify.kt
app/src/main/java/com/getcode/view/login/SeedInput.kt
app/src/main/java/com/getcode/view/main/account/ConfirmDeleteAccount.kt
app/src/main/java/com/getcode/view/main/account/DeleteAccount.kt

* Ripple colors when ButtonState.Filled
* Enter Phone number hint alignment
* BottomBarBanner text color on filled button
* Vertical padding between seed input and submit button
* navbar padding across screens
* Access Key screen move hint move up with key and change color

style(login): ui improvements from design review

---

app/src/main/java/com/getcode/CodeApp.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/navigation/screens/Modals.kt
app/src/main/java/com/getcode/util/AnimationUtils.kt
app/src/main/java/com/getcode/view/main/home/HomeScan.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

Also clean up transitions into login and into home

fix(home): vibrate on bill grabbed

---

api/src/main/java/com/getcode/network/repository/TransactionRepository.kt
app/src/main/java/com/getcode/navigation/screens/MainScreens.kt
app/src/main/java/com/getcode/navigation/screens/WithdrawalScreens.kt
app/src/main/java/com/getcode/view/login/PhoneConfirm.kt
app/src/main/java/com/getcode/view/login/PhoneVerify.kt
app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmount.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheetViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountArea.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountText.kt
app/src/main/java/com/getcode/view/main/giveKin/BaseAmountCurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheet.kt

* Consistent hint text style
* Enter phone number hint inset
* Phone number vertical alignment in TextField
* Layout adjustments to better support imePadding

chore(phone): layout adjustments

---

api/src/main/java/com/getcode/network/BalanceController.kt
api/src/main/java/com/getcode/network/exchange/Exchange.kt
app/src/main/java/com/getcode/view/main/bill/Bill.kt
app/src/main/java/com/getcode/view/main/bill/PaymentReceiptBill.kt
app/src/main/java/com/getcode/view/main/home/HomeScan.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt
app/src/main/java/com/getcode/view/main/home/components/PaymentConfirmation.kt
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values/strings.xml

feat(micropayments): add insufficient funds modal to micropayments flow when applicable

---

api/src/main/java/com/getcode/network/client/Client_Transaction.kt
api/src/main/java/com/getcode/network/repository/TransactionRepository.kt
api/src/main/java/com/getcode/utils/network/NetworkConnectionListener.kt
app/src/main/java/com/getcode/TopLevelViewModel.kt
app/src/main/java/com/getcode/manager/AuthManager.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheetViewModel.kt
app/src/main/java/com/getcode/view/main/getKin/GetKinSheetViewModel.kt
app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

prevent repopulating the transaction cache after setting to null on logout

chore: add more robust handling to transaction scanning

---

app/src/main/java/com/getcode/view/main/home/HomeScan.kt

fix(bill/exit): await for full settle before enabling cancel

---

app/src/main/java/com/getcode/util/Currency.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectionSheet.kt
app/src/main/java/com/getcode/view/main/currency/CurrencyViewModel.kt

don't add to recents before navigating home
don't partially swipe back when removing from recents

chore: improve ux in currency selection sheet

---

app/src/main/java/com/getcode/view/main/giveKin/AmountArea.kt

was implemented as Alignment.CenterVertically with an offset padding?

chore: align raw kin amount in AmountArea

---

app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

only need to toast in the payment currency, not the localized one

fix(payments): prevent toast changing currency midflight

---

api/src/main/java/com/getcode/network/client/TransactionReceiver.kt

swift guards always throw me for a loop

fix(api): actually guard against empty balances

---

app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmountViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/BaseAmountCurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinSheetViewModel.kt

* reset entered amount when changing
* no decimals with Kin

chore: handle currency changes

---

app/src/main/java/com/getcode/ui/components/SlideToConfirm.kt
app/src/main/java/com/getcode/view/main/home/components/LoginConfirmation.kt
app/src/main/java/com/getcode/view/main/home/components/PaymentConfirmation.kt

* make thumb square
* keep cancel button bounds consistent

style: slide to confirm UI tweaks

---

app/src/main/java/com/getcode/ui/components/SlideToConfirm.kt

https://github.com/code-payments/code-android-app/assets/1652321/d4446c79-e156-441a-bca0-6f8d03dd6694

feat: add spring hint to SlideToConfirm

---

app/src/main/java/com/getcode/view/main/account/AccountHome.kt

chore: push BuyKin and BuySell sheets in instead of show

---

api/src/main/java/com/getcode/network/repository/Extensions.kt

Updated localization handling brought in param positioning; update replaceParam to support vararg and replace per index

chore: make string param replacement support positioning

---

buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties

- kotlin
- AGP
- Compose
- Compose Compiler
- Gradle

chore: update some dependencies

---

api/src/main/java/com/getcode/model/Feature.kt
api/src/main/java/com/getcode/model/PrefBool.kt
api/src/main/java/com/getcode/model/PrefString.kt
api/src/main/java/com/getcode/network/BalanceController.kt
api/src/main/java/com/getcode/network/client/TransactionReceiver.kt
api/src/main/java/com/getcode/network/repository/AccountRepository.kt
api/src/main/java/com/getcode/network/repository/BetaFlagsRepository.kt
api/src/main/java/com/getcode/network/repository/FeatureRepository.kt
app/src/main/java/com/getcode/inject/ApiModule.kt
app/src/main/java/com/getcode/navigation/screens/ChatScreens.kt
app/src/main/java/com/getcode/navigation/screens/ModalScreens.kt
app/src/main/java/com/getcode/ui/components/chat/MessageTextContent.kt
app/src/main/java/com/getcode/view/main/account/BetaFlagsScreen.kt
app/src/main/java/com/getcode/view/main/account/BetaFlagsViewModel.kt
app/src/main/java/com/getcode/view/main/account/withdraw/AccountWithdrawAmount.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheet.kt
app/src/main/java/com/getcode/view/main/balance/BalanceSheetViewModel.kt
app/src/main/java/com/getcode/view/main/currency/CurrencySelectionSheet.kt
app/src/main/java/com/getcode/view/main/currency/CurrencyViewModel.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountArea.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountText.kt
app/src/main/java/com/getcode/view/main/giveKin/AmountTextAnimated.kt
app/src/main/java/com/getcode/view/main/giveKin/GiveKinScreen.kt
app/src/main/java/com/getcode/view/main/requestKin/RequestKinScreen.kt
app/src/main/java/com/getcode/view/main/tip/EnterTipScreen.kt
app/src/main/res/values/strings-universal.xml

feat: add currency selection in balance screen

---

app/src/main/java/com/getcode/view/main/home/HomeViewModel.kt

* keep tip cards on screen when not activated banner is present
* allow invalid cards to be rescanned

chore(home): tip not activated improvements

---

api/src/main/java/com/getcode/network/BalanceController.kt
api/src/main/java/com/getcode/utils/Logging.kt
api/src/main/java/com/getcode/utils/Timber.kt
app/src/main/java/com/getcode/Session.kt
app/src/main/java/com/getcode/view/main/scanner/ScannerScreen.kt
app/src/main/java/com/getcode/view/main/scanner/camera/CodeScanner.kt
app/src/main/java/com/getcode/view/main/scanner/views/CameraDisabledView.kt
app/src/main/java/com/kik/kikx/kikcodes/implementation/KikCodeAnalyzer.kt
app/src/main/java/com/kik/kikx/kikcodes/implementation/StaticImageHelper.kt
app/src/main/res/values/strings.xml

move timedTrace durations to trace metedata
remove loading state during image processing

chore: improve sliding window search for static images

---

api/src/main/java/com/getcode/model/chat/ChatStreamEventUpdate.kt
api/src/main/java/com/getcode/network/ConversationController.kt
api/src/main/java/com/getcode/network/api/ChatApiV2.kt
api/src/main/java/com/getcode/network/service/ChatServiceV2.kt
app/src/main/java/com/getcode/navigation/screens/Modals.kt
app/src/main/java/com/getcode/ui/components/chat/ChatInput.kt
app/src/main/java/com/getcode/ui/components/chat/DateWithStatus.kt
app/src/main/java/com/getcode/ui/components/chat/MessageNode.kt
app/src/main/java/com/getcode/ui/components/chat/TypingIndicator.kt
app/src/main/java/com/getcode/view/main/chat/conversation/ConversationScreen.kt
app/src/main/java/com/getcode/view/main/chat/conversation/ConversationViewModel.kt
common/theme/src/main/kotlin/com/getcode/theme/Color.kt
common/theme/src/main/kotlin/com/getcode/theme/Theme.kt

feat(chat): add typing indicator

---

app/src/main/java/com/getcode/ui/components/chat/ChatNode.kt
app/src/main/java/com/getcode/view/main/chat/list/ChatListScreen.kt

chore: make avatars in ChatNode opt-in

---

services/flipchat/sdk/src/main/kotlin/xyz/flipchat/chat/paging/MessagingPagingSource.kt

Prevent the chat scrolling in on open

Flipchat release 1.0.5
